### ISSUE TITLE
Multiple environments get added an SSH key even though only 1 environment was chosen to add SSH key 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/tray#262]
![image](https://user-images.githubusercontent.com/17665678/30960512-09a06fee-a465-11e7-8399-996e51fc2d70.png)
Steps: 
1. Create2-3 environments
2. Add SSH key from Tray to only 1 of them
Result: 
Mutiple envionments get added SSH key 
Extras: 
This is happening on `Windows 8.1` 
Tray version: 
![image](https://user-images.githubusercontent.com/17665678/30960659-8232cf42-a465-11e7-8fc9-a2b1a3034416.png)

**Comment by SEFI2** [comment]
It is possible that you choose one Environment and get this result, when, for example, you unchecked already chosen an environment and checked the new one. I mean, if you have A as checked and B as unchecked, but if you are trying to uncheck A, check B and save changes, then it is OK for both of environments to go UNDER MODIFICATION since you change both of environments. BUT if both of A and B was unchecked, but you choose only one and saved the changes, it means it's bug.

Can you please give some details about your steps. I am testing it now, but couldn't reproduce it.

**Comment by akylbekesenaliev** [comment]
@SEFI2 sure

I have created like 5 environments then generated an SSH key, then added the SSH key to one environment, but before trying to add the SSH key, one of my environments had an SSH key inside already and it was checked- I did uncheck it, then checked another environment and then I went to Hub to see if any changes are being made, and there I saw 2 environments with UNDER_MODIFICATION statuses, though I checked only one environment and previously unchecked one environment too.

**Comment by akylbekesenaliev** [comment]
Tested - did not encounter this issue.
