### ISSUE TITLE
"Launch Subutai console" button.

### ISSUE THREAD

**Issue by Shahrizada** [subutai-io/tray#434]
Tray shows "Launch Subutai console" button active even if I don't have a RH. This button needs to be disabled and given some notification or even given a link to instruction documentation or videos.
![screen shot 2017-12-04 at 20 25 56](https://user-images.githubusercontent.com/31571523/33557872-a90ed316-d932-11e7-85f5-aaab3e3fe398.png)

**Comment by SEFI2** [comment]
@Shahrizada Thank you for this useful feedback. I think we can remove this button completely, because in near future we are planning to enable users to launch consoles for `multiple peers`, it means for each Peer there will be one button. But for now, we will make `launch button` disabled if users don't have any Peers.

**Comment by amol4anoff** [comment]
Done.
